name: "learn"

on:
    workflow_dispatch:

jobs:
    echo:
        name: "echo"
        runs-on: ubuntu-22.04
        timeout-minutes: 30

        steps:
            - name: echo
              run: echo "hello world"